# Generated by Django 3.1a1 on 2020-06-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
